export const awardStations = {
  "tien-giang": "Tiền Giang",
  "kien-giang": "Kiên Giang",
  "da-lat": "Đà Lạt",
  "khanh-hoa": "Khánh Hòa",
  "kon-tum": "Kon Tum",
  "tp-hcm": "Tp. HCM",
  "dong-thap": "Đồng Tháp",
  "ca-mau": "Cà Mau",
  "thua-thien-hue": "Thừa T. Huế",
  "phu-yen": "Phú Yên",
  "ben-tre": "Bến Tre",
  "vung-tau": "Vũng Tàu",
  "bac-lieu": "Bạc Liêu",
  "quang-nam": "Quảng Nam",
  "dak-lak": "Đắk lắk",
  "dong-nai": "Đồng Nai",
  "can-tho": "Cần Thơ",
  "soc-trang": "Sóc Trăng",
  "da-nang": "Đà Nẵng",
  "tay-ninh": "Tây Ninh",
  "an-giang": "An Giang",
  "binh-thuan": "Bình Thuận",
  "binh-dinh": "Bình Định",
  "quang-binh": "Quảng Bình",
  "quang-tri": "Quảng Trị",
  "vinh-long": "Vĩnh Long",
  "binh-duong": "Bình Dương",
  "tra-vinh": "Trà Vinh",
  "gia-lai": "Gia Lai",
  "ninh-thuan": "Ninh Thuận",
  "long-an": "Long An",
  "hau-giang": "Hậu Giang",
  "binh-phuoc": "Bình Phước",
  "quang-ngai": "Quảng Ngãi",
  "dak-nong": "Đắk Nông",
};

export const awardType = {
  giaidb: "Giải Đặc Biệt",
  giai1: "Giải nhất",
  giai2: "Giải nhì",
  giai3: "Giải ba",
  giai4: "Giải tư",
  giai5: "Giải năm",
  giai6: "Giải sáu",
  giai7: "Giải bảy",
  giai8: "Giải tám",
};
