/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateCustomerRouteImport } from './routes/create-customer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appHomeRouteImport } from './routes/(app)/home'
import { Route as appCustomerIndexRouteImport } from './routes/(app)/customer/index'
import { Route as appCustomerLayoutRouteImport } from './routes/(app)/customer/layout'
import { Route as appCustomerCustomerIdRouteImport } from './routes/(app)/customer/$customerId'
import { Route as appauthSignUpRouteImport } from './routes/(app)/(auth)/sign-up'
import { Route as appauthSignInRouteImport } from './routes/(app)/(auth)/sign-in'
import { Route as appCustomerCustomerIdIndexRouteImport } from './routes/(app)/customer/$customerId/index'
import { Route as appCustomerCustomerIdAddRouteImport } from './routes/(app)/customer/$customerId/add'

const CreateCustomerRoute = CreateCustomerRouteImport.update({
  id: '/create-customer',
  path: '/create-customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appHomeRoute = appHomeRouteImport.update({
  id: '/(app)/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const appCustomerIndexRoute = appCustomerIndexRouteImport.update({
  id: '/(app)/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const appCustomerLayoutRoute = appCustomerLayoutRouteImport.update({
  id: '/(app)/customer/layout',
  path: '/customer/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appCustomerCustomerIdRoute = appCustomerCustomerIdRouteImport.update({
  id: '/(app)/customer/$customerId',
  path: '/customer/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const appauthSignUpRoute = appauthSignUpRouteImport.update({
  id: '/(app)/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const appauthSignInRoute = appauthSignInRouteImport.update({
  id: '/(app)/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const appCustomerCustomerIdIndexRoute =
  appCustomerCustomerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appCustomerCustomerIdRoute,
  } as any)
const appCustomerCustomerIdAddRoute =
  appCustomerCustomerIdAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => appCustomerCustomerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-customer': typeof CreateCustomerRoute
  '/home': typeof appHomeRoute
  '/sign-in': typeof appauthSignInRoute
  '/sign-up': typeof appauthSignUpRoute
  '/customer/$customerId': typeof appCustomerCustomerIdRouteWithChildren
  '/customer/layout': typeof appCustomerLayoutRoute
  '/customer/': typeof appCustomerIndexRoute
  '/customer/$customerId/add': typeof appCustomerCustomerIdAddRoute
  '/customer/$customerId/': typeof appCustomerCustomerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-customer': typeof CreateCustomerRoute
  '/home': typeof appHomeRoute
  '/sign-in': typeof appauthSignInRoute
  '/sign-up': typeof appauthSignUpRoute
  '/customer/layout': typeof appCustomerLayoutRoute
  '/customer': typeof appCustomerIndexRoute
  '/customer/$customerId/add': typeof appCustomerCustomerIdAddRoute
  '/customer/$customerId': typeof appCustomerCustomerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-customer': typeof CreateCustomerRoute
  '/(app)/home': typeof appHomeRoute
  '/(app)/(auth)/sign-in': typeof appauthSignInRoute
  '/(app)/(auth)/sign-up': typeof appauthSignUpRoute
  '/(app)/customer/$customerId': typeof appCustomerCustomerIdRouteWithChildren
  '/(app)/customer/layout': typeof appCustomerLayoutRoute
  '/(app)/customer/': typeof appCustomerIndexRoute
  '/(app)/customer/$customerId/add': typeof appCustomerCustomerIdAddRoute
  '/(app)/customer/$customerId/': typeof appCustomerCustomerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-customer'
    | '/home'
    | '/sign-in'
    | '/sign-up'
    | '/customer/$customerId'
    | '/customer/layout'
    | '/customer/'
    | '/customer/$customerId/add'
    | '/customer/$customerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-customer'
    | '/home'
    | '/sign-in'
    | '/sign-up'
    | '/customer/layout'
    | '/customer'
    | '/customer/$customerId/add'
    | '/customer/$customerId'
  id:
    | '__root__'
    | '/'
    | '/create-customer'
    | '/(app)/home'
    | '/(app)/(auth)/sign-in'
    | '/(app)/(auth)/sign-up'
    | '/(app)/customer/$customerId'
    | '/(app)/customer/layout'
    | '/(app)/customer/'
    | '/(app)/customer/$customerId/add'
    | '/(app)/customer/$customerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateCustomerRoute: typeof CreateCustomerRoute
  appHomeRoute: typeof appHomeRoute
  appauthSignInRoute: typeof appauthSignInRoute
  appauthSignUpRoute: typeof appauthSignUpRoute
  appCustomerCustomerIdRoute: typeof appCustomerCustomerIdRouteWithChildren
  appCustomerLayoutRoute: typeof appCustomerLayoutRoute
  appCustomerIndexRoute: typeof appCustomerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-customer': {
      id: '/create-customer'
      path: '/create-customer'
      fullPath: '/create-customer'
      preLoaderRoute: typeof CreateCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/home': {
      id: '/(app)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof appHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/customer/': {
      id: '/(app)/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof appCustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/customer/layout': {
      id: '/(app)/customer/layout'
      path: '/customer/layout'
      fullPath: '/customer/layout'
      preLoaderRoute: typeof appCustomerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/customer/$customerId': {
      id: '/(app)/customer/$customerId'
      path: '/customer/$customerId'
      fullPath: '/customer/$customerId'
      preLoaderRoute: typeof appCustomerCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(auth)/sign-up': {
      id: '/(app)/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof appauthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(auth)/sign-in': {
      id: '/(app)/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof appauthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/customer/$customerId/': {
      id: '/(app)/customer/$customerId/'
      path: '/'
      fullPath: '/customer/$customerId/'
      preLoaderRoute: typeof appCustomerCustomerIdIndexRouteImport
      parentRoute: typeof appCustomerCustomerIdRoute
    }
    '/(app)/customer/$customerId/add': {
      id: '/(app)/customer/$customerId/add'
      path: '/add'
      fullPath: '/customer/$customerId/add'
      preLoaderRoute: typeof appCustomerCustomerIdAddRouteImport
      parentRoute: typeof appCustomerCustomerIdRoute
    }
  }
}

interface appCustomerCustomerIdRouteChildren {
  appCustomerCustomerIdAddRoute: typeof appCustomerCustomerIdAddRoute
  appCustomerCustomerIdIndexRoute: typeof appCustomerCustomerIdIndexRoute
}

const appCustomerCustomerIdRouteChildren: appCustomerCustomerIdRouteChildren = {
  appCustomerCustomerIdAddRoute: appCustomerCustomerIdAddRoute,
  appCustomerCustomerIdIndexRoute: appCustomerCustomerIdIndexRoute,
}

const appCustomerCustomerIdRouteWithChildren =
  appCustomerCustomerIdRoute._addFileChildren(
    appCustomerCustomerIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateCustomerRoute: CreateCustomerRoute,
  appHomeRoute: appHomeRoute,
  appauthSignInRoute: appauthSignInRoute,
  appauthSignUpRoute: appauthSignUpRoute,
  appCustomerCustomerIdRoute: appCustomerCustomerIdRouteWithChildren,
  appCustomerLayoutRoute: appCustomerLayoutRoute,
  appCustomerIndexRoute: appCustomerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
