/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoffRouteImport } from './routes/layoff'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersCreateRouteImport } from './routes/customers/create'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as CustomersCustomerIdIndexRouteImport } from './routes/customers/$customerId/index'
import { Route as CustomersCustomerIdMessageRouteImport } from './routes/customers/$customerId/message'
import { Route as CustomersCustomerIdOrderIdEditRouteImport } from './routes/customers/$customerId/$orderId.edit'

const LayoffRoute = LayoffRouteImport.update({
  id: '/layoff',
  path: '/layoff',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCreateRoute = CustomersCreateRouteImport.update({
  id: '/customers/create',
  path: '/customers/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdIndexRoute =
  CustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomersCustomerIdMessageRoute =
  CustomersCustomerIdMessageRouteImport.update({
    id: '/customers/$customerId/message',
    path: '/customers/$customerId/message',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomersCustomerIdOrderIdEditRoute =
  CustomersCustomerIdOrderIdEditRouteImport.update({
    id: '/customers/$customerId/$orderId/edit',
    path: '/customers/$customerId/$orderId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/layoff': typeof LayoffRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/customers/create': typeof CustomersCreateRoute
  '/customers/': typeof CustomersIndexRoute
  '/customers/$customerId/message': typeof CustomersCustomerIdMessageRoute
  '/customers/$customerId/': typeof CustomersCustomerIdIndexRoute
  '/customers/$customerId/$orderId/edit': typeof CustomersCustomerIdOrderIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/layoff': typeof LayoffRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/customers/create': typeof CustomersCreateRoute
  '/customers': typeof CustomersIndexRoute
  '/customers/$customerId/message': typeof CustomersCustomerIdMessageRoute
  '/customers/$customerId': typeof CustomersCustomerIdIndexRoute
  '/customers/$customerId/$orderId/edit': typeof CustomersCustomerIdOrderIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/layoff': typeof LayoffRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/customers/create': typeof CustomersCreateRoute
  '/customers/': typeof CustomersIndexRoute
  '/customers/$customerId/message': typeof CustomersCustomerIdMessageRoute
  '/customers/$customerId/': typeof CustomersCustomerIdIndexRoute
  '/customers/$customerId/$orderId/edit': typeof CustomersCustomerIdOrderIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/layoff'
    | '/auth/sign-up'
    | '/customers/create'
    | '/customers/'
    | '/customers/$customerId/message'
    | '/customers/$customerId/'
    | '/customers/$customerId/$orderId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/layoff'
    | '/auth/sign-up'
    | '/customers/create'
    | '/customers'
    | '/customers/$customerId/message'
    | '/customers/$customerId'
    | '/customers/$customerId/$orderId/edit'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/layoff'
    | '/auth/sign-up'
    | '/customers/create'
    | '/customers/'
    | '/customers/$customerId/message'
    | '/customers/$customerId/'
    | '/customers/$customerId/$orderId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LayoffRoute: typeof LayoffRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  CustomersCreateRoute: typeof CustomersCreateRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  CustomersCustomerIdMessageRoute: typeof CustomersCustomerIdMessageRoute
  CustomersCustomerIdIndexRoute: typeof CustomersCustomerIdIndexRoute
  CustomersCustomerIdOrderIdEditRoute: typeof CustomersCustomerIdOrderIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/layoff': {
      id: '/layoff'
      path: '/layoff'
      fullPath: '/layoff'
      preLoaderRoute: typeof LayoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/create': {
      id: '/customers/create'
      path: '/customers/create'
      fullPath: '/customers/create'
      preLoaderRoute: typeof CustomersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/': {
      id: '/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof CustomersCustomerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/message': {
      id: '/customers/$customerId/message'
      path: '/customers/$customerId/message'
      fullPath: '/customers/$customerId/message'
      preLoaderRoute: typeof CustomersCustomerIdMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/$orderId/edit': {
      id: '/customers/$customerId/$orderId/edit'
      path: '/customers/$customerId/$orderId/edit'
      fullPath: '/customers/$customerId/$orderId/edit'
      preLoaderRoute: typeof CustomersCustomerIdOrderIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LayoffRoute: LayoffRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  CustomersCreateRoute: CustomersCreateRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  CustomersCustomerIdMessageRoute: CustomersCustomerIdMessageRoute,
  CustomersCustomerIdIndexRoute: CustomersCustomerIdIndexRoute,
  CustomersCustomerIdOrderIdEditRoute: CustomersCustomerIdOrderIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
